In [22]:
import pandas as pd
import pronto
from collections import deque
from typing import Tuple, Dict, Set, List
from collections import defaultdict

In [3]:
df_clinical = pd.read_csv("/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mapped_all/mapped_clinical_data.csv", dtype=str)
df_preclinical = pd.read_csv("/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mapped_all/mapped_preclinical_data_enriched.csv", dtype=str)

In [4]:
df_clinical.shape, df_preclinical.shape

((18609, 8), (547365, 9))

In [7]:
umls_full = pd.read_csv("/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/umls/mrconso_filtered_db_and_sty_474316_drug_chemical_level_0_9.csv")

In [9]:
umls_full.head()

,cui,srl,sab,str,sty
0,C5687455,9,SNOMEDCT_US,Solution for infusion and/or injection,Biomedical or Dental Material
1,C5687658,9,SNOMEDCT_US,Amlodipine- and atenolol-containing product in...,Clinical Drug
2,C5688824,9,SNOMEDCT_US,Prolonged-release periodontal insert,Biomedical or Dental Material
3,C5690295,0,MSH,ACEA100610,Organic Chemical
4,C5690315,0,MSH,"MIRN3113 microRNA, human",Biologically Active Substance

In [20]:
cui_to_str = pd.Series(umls_full['str'].values, index=umls_full['cui']).to_dict()
cui_to_str['C5198068']

'fty720-c2'

In [5]:
mappings = pd.read_csv("/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/umls/mrrel_mapped_to_form_of_20251112.csv")

In [17]:
mappings.rela.unique()

array(['mapped_to', 'form_of'], dtype=object)

In [6]:
mappings.head()

,cui1,aui1,stype1,rel,cui2,aui2,stype2,rela,rui,srui,sab,sl,rg,dir,suppress,cvf,dummy
0,C0000173,A0016717,SDUI,RN,C0044909,A0140525,SDUI,mapped_to,R148187775,NaN,MSH,MSH,1.0,NaN,N,NaN,NaN
1,C0000173,A0016717,SDUI,RN,C0045030,A0140860,SDUI,mapped_to,R148219995,NaN,MSH,MSH,1.0,NaN,N,NaN,NaN
2,C0000173,A0016717,SDUI,RN,C0045031,A0140863,SDUI,mapped_to,R148193004,NaN,MSH,MSH,1.0,NaN,N,NaN,NaN
3,C0000173,A0016717,SDUI,RN,C0601554,A1326303,SDUI,mapped_to,R148155163,NaN,MSH,MSH,1.0,NaN,N,NaN,NaN
4,C0000173,A0016717,SDUI,RN,C0609759,A1326223,SDUI,mapped_to,R148209126,NaN,MSH,MSH,1.0,NaN,N,NaN,NaN

In [26]:
cui2_to_cui1 = defaultdict(list)

# build mapping
for _, row in mappings.iterrows():
    cui1 = row['cui1'].strip()
    cui2 = row['cui2'].strip()
    if pd.notna(cui1) and pd.notna(cui2):
        cui2_to_cui1[cui2].append(cui1)

# optionally convert to a normal dict
cui2_to_cui1 = dict(cui2_to_cui1)

In [32]:
id_to_map = "C5198068"
print(f"{id_to_map} is {cui_to_str[id_to_map]}")
for mapping in cui2_to_cui1[id_to_map]:
    print(f"-> maps to {cui_to_str[mapping]}")
    if mapping in cui2_to_cui1:
        for deeper_map in cui2_to_cui1[mapping]:
            print(f"--> maps to {cui_to_str[deeper_map]}")

C5198068 is fty720-c2
-> maps to Ceramides
-> maps to Fingolimod hydrochloride
--> maps to Fingolimod

In [ ]:
id_to_map = "C5198068"
print(f"{id_to_map} is {cui_to_str[id_to_map]}")
for mapping in cui2_to_cui1[id_to_map]:
    print(f"-> maps to {cui_to_str[mapping]}")
    if mapping in cui2_to_cui1:
        for deeper_map in cui2_to_cui1[mapping]:
            print(f"--> maps to {cui_to_str[deeper_map]}")